### ISSUE TITLE
Сонар. Ошибка сканера при парсинге generic issue  - 0 is not a valid line for a file

### ISSUE THREAD

**Issue by IT-Medved** [Stepa86/stebi#1]
Выполнение сонар сканера завершается с ошибкой ,когда в результатах анализа присутствует строка как в примере.

Ошибка сканера :

11:37:32  INFO: ------------------------------------------------------------------------
11:37:32  INFO: EXECUTION FAILURE
11:37:32  INFO: ------------------------------------------------------------------------
11:37:32  INFO: Total time: 11.731s
11:37:32  INFO: Final Memory: 14M/6144M
11:37:32  INFO: ------------------------------------------------------------------------
11:37:32  ERROR: Error during SonarQube Scanner execution
11:37:32  java.lang.IllegalArgumentException: 0 is not a valid line for a file

Пример edt : 
2021-10-02T11:28:59+0300	Ошибка	configuration	ОбщаяФорма.ЛучшаяФорма.Форма.Модуль	строка 0	Error executing EValidator

Пример GI:

`{
"issues": [
{
"engineId": "edt",
"ruleId": "Error executing EValidator",
"primaryLocation": {
"message": "Error executing EValidator",
"filePath": "c:/rep/project/configuration/src/CommonForms/ЛучшаяФорма/Module.bsl",
"textRange": {
"startLine": 0
}
},
"type": "BUG",
"severity": "CRITICAL",
"effortMinutes": 0,
"secondaryLocations": []
}
],
"rules": [
{
"engineId": "edt",
"ruleId": "Error executing EValidator",
"name": "Error executing EValidator",
"type": "BUG",
"severity": "CRITICAL",
"description": "Error executing EValidator"
}
]
}`

**Comment by Stepa86** [comment]
Так то это проверка в едт рухнула. Но согласен, что это не должно ронять и сонар
