### ISSUE TITLE
Удаление файлов на поддержке. Поясните как работает

### ISSUE THREAD

**Issue by VosmirkoSergey** [Stepa86/stebi#8]
Добрый день. Пытаюсь с помощью вашей разработки из исходных кодов проекта 1С выполнить удаление файлов на поддержке, чтобы сонар куб их не проверял

Не очень понимаю как это работает. 
- Вы в каталоге с исходными кодами удаляете файлы?
- Или на выходе получается некий файл настройки в котором перечислены модули которые нужно проверять, а файлы с модулями на поддержке там не перечислены.
  И этот файл надо как-то сонару подсунуть.

Могли бы пояснить поподробнее?

**Comment by Stepa86** [comment]
Приложение stebi генерирует файл с ошибками в формате generic issue для плагина https://github.com/1c-syntax/sonar-bsl-plugin-community на основе файла с ошибками от ЕДТ. И умеет удалять ошибки из этого файла по тем файлам, которые на поддержке. 

Приложение ничего не удаляет из исходников.

Если для сонара не используется проверка средствами едт с загрузкой ошибок через generic issue, то для исключения ошибок по файлам на поддержке нужно использовать средства плагина: параметр `sonar.bsl.languageserver.skipSupport` https://1c-syntax.github.io/sonar-bsl-plugin-community/

Если вы разворачиваете себе пайплайн для сонара с нуля, то рекомендую идти от https://github.com/firstBitMarksistskaya/jenkins-lib  . Есть стрим по нему: https://www.youtube.com/watch?v=86wJ-ldntAo

**Comment by VosmirkoSergey** [comment]
большое спасибо! Теперь понятно )
